(() => {
  // <stdin>
  console.log("This site was generated by Hugo.");
  var ColumnStyleLoader = class {
    constructor() {
      this.observer = new MutationObserver((mutations) => {
        mutations.forEach((mutation) => {
          mutation.addedNodes.forEach((node) => {
            if (node.classList?.contains("column-base")) {
              this.loadCustomStyle(node);
            }
          });
        });
      });
      this.observer.observe(document.body, {
        childList: true,
        subtree: true
      });
    }
    loadCustomStyle(column) {
      const cssPath = column.dataset.customCss;
      if (cssPath && !document.querySelector(`link[href="${cssPath}"]`)) {
        const link = document.createElement("link");
        link.rel = "stylesheet";
        link.href = cssPath;
        document.head.appendChild(link);
      }
    }
  };
  new ColumnStyleLoader();
})();
